language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - coverage run --source=api manage.py test api

script:
  - python chisalary/manage.py test api -v 2
