version: '2'

services:
  db:
    image: postgres:latest
    hostname: db
    ports:
      - "5432:5432"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile
    hostname: web
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /chisalary
    volumes:
      - ./chisalary:/chisalary
    ports:
      - "8000:8000"
    links:
      - db
      - rabbitmq
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: tools/docker/Dockerfile
    command: celery -A chisalary worker -l info
    working_dir: /chisalary
    volumes:
      - ./chisalary:/chisalary
    links:
      - db
      - rabbitmq
    depends_on:
      - rabbitmq

  beat:
      build:
        context: .
        dockerfile: tools/docker/Dockerfile
      command: celery -A chisalary beat -l info
      working_dir: /chisalary
      volumes:
        - ./chisalary:/chisalary
      links:
        - db
        - rabbitmq
      depends_on:
        - rabbitmq
