# Generated by Django 2.0 on 2017-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('job_titles', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=64)),
                ('full_or_part_time', models.CharField(max_length=16)),
                ('salary_or_hourly', models.CharField(max_length=16)),
                ('typical_hours', models.IntegerField(null=True)),
                ('annual_salary', models.CharField(max_length=32)),
                ('hourly_rate', models.CharField(max_length=32)),
            ],
        ),
    ]
