# Generated by Django 2.0 on 2017-12-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171216_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_salary',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
