# Generated by Django 2.0 on 2017-12-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171216_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
